create table bank (
	account_number BIGINT NOT NULL PRIMARY KEY,
	person_id BIGSERIAL NOT NULL,
	balance VARCHAR(50) NOT NULL,
	account_type VARCHAR(10) NOT NULL
);
insert into bank (account_number, balance, account_type) values (585665572, 'Krone', 'Investment');
insert into bank (account_number, balance, account_type) values (70389447, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (126763858, 'Bolivar', 'Checking');
insert into bank (account_number, balance, account_type) values (131991236, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (254465757, 'Ariary', 'Investment');
insert into bank (account_number, balance, account_type) values (405982946, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (562713842, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (453963062, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (388138929, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (368382417, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (892512630, 'Pound', 'Savings');
insert into bank (account_number, balance, account_type) values (548742013, 'Balboa', 'Investment');
insert into bank (account_number, balance, account_type) values (920037970, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (499380153, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (728832900, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (317577953, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (941069537, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (777457533, 'Krone', 'Investment');
insert into bank (account_number, balance, account_type) values (243475922, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (185135657, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (208600668, 'Ringgit', 'Investment');
insert into bank (account_number, balance, account_type) values (777443593, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (115669179, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (443551958, 'Lempira', 'Checking');
insert into bank (account_number, balance, account_type) values (728795356, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (21375545, 'Pound', 'Savings');
insert into bank (account_number, balance, account_type) values (992857969, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (295631515, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (228881763, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (291011225, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (377787581, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (258555504, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (381123671, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (691165070, 'Tenge', 'Savings');
insert into bank (account_number, balance, account_type) values (799638523, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (465879646, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (823882910, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (264351026, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (689768322, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (354213510, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (232665456, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (219820656, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (459640810, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (655979818, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (314163068, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (956400896, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (568653692, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (979274429, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (745003042, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (823353091, 'Ringgit', 'Savings');
insert into bank (account_number, balance, account_type) values (476081763, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (644136823, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (321360242, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (736271930, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (868346620, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (792625022, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (978420315, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (63474147, 'Franc', 'Savings');
insert into bank (account_number, balance, account_type) values (342218265, 'Kwanza', 'Checking');
insert into bank (account_number, balance, account_type) values (909305235, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (496730925, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (141754583, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (628689254, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (983651875, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (190311152, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (827681015, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (506457554, 'Boliviano', 'Checking');
insert into bank (account_number, balance, account_type) values (880084825, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (589845480, 'Yen', 'Checking');
insert into bank (account_number, balance, account_type) values (985427405, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (583329159, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (520628089, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (571332483, 'Kwacha', 'Savings');
insert into bank (account_number, balance, account_type) values (781195406, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (346859754, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (148607480, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (772792292, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (33209862, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (614994296, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (682785653, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (710076097, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (821348944, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (949736728, 'Tenge', 'Checking');
insert into bank (account_number, balance, account_type) values (782945691, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (756683510, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (813704634, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (456206456, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (798042518, 'Krone', 'Investment');
insert into bank (account_number, balance, account_type) values (823200099, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (707318552, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (242567230, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (571612469, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (192818520, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (316393598, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (17233639, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (727305218, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (811871446, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (919815767, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (791006884, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (562666556, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (132753190, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (652274057, 'Dirham', 'Checking');
insert into bank (account_number, balance, account_type) values (284635917, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (684462305, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (332450252, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (58531194, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (584119221, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (945628833, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (930337383, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (550094679, 'Leone', 'Savings');
insert into bank (account_number, balance, account_type) values (124338464, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (670296259, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (804058129, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (98668544, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (726872290, 'Manat', 'Checking');
insert into bank (account_number, balance, account_type) values (92984349, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (44632657, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (347263789, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (872777363, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (478410111, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (806406088, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (733308395, 'Franc', 'Checking');
insert into bank (account_number, balance, account_type) values (552840077, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (371168843, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (216357716, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (551390433, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (486628785, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (121887154, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (659862162, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (523465305, 'Yen', 'Investment');
insert into bank (account_number, balance, account_type) values (53825938, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (782363726, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (630239133, 'Won', 'Checking');
insert into bank (account_number, balance, account_type) values (460016734, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (316946435, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (195622422, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (314632907, 'Rand', 'Savings');
insert into bank (account_number, balance, account_type) values (171021008, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (146111693, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (469646265, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (458940252, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (399691151, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (307383966, 'Koruna', 'Checking');
insert into bank (account_number, balance, account_type) values (659022974, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (365998768, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (139037976, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (590434729, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (693871186, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (23746930, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (29257194, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (978092644, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (44970902, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (1249229, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (264276254, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (28284380, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (528054221, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (483458883, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (455705486, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (942518249, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (263466767, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (711565744, 'Ringgit', 'Savings');
insert into bank (account_number, balance, account_type) values (130664338, 'Shilling', 'Savings');
insert into bank (account_number, balance, account_type) values (722372213, 'Guarani', 'Savings');
insert into bank (account_number, balance, account_type) values (949124768, 'Franc', 'Savings');
insert into bank (account_number, balance, account_type) values (811816327, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (298085484, 'Balboa', 'Savings');
insert into bank (account_number, balance, account_type) values (560177087, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (420363690, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (167791539, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (709715745, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (902471151, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (513118347, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (801359284, 'Kuna', 'Investment');
insert into bank (account_number, balance, account_type) values (832874565, 'Quetzal', 'Checking');
insert into bank (account_number, balance, account_type) values (805782045, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (314461110, 'Shekel', 'Investment');
insert into bank (account_number, balance, account_type) values (526545292, 'Franc', 'Investment');
insert into bank (account_number, balance, account_type) values (275449357, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (731072164, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (208362229, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (656448361, 'Shekel', 'Savings');
insert into bank (account_number, balance, account_type) values (132599040, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (684863843, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (73443561, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (62964618, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (191863331, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (638012952, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (693357521, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (160654255, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (83358852, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (450117449, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (502347527, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (276848526, 'Dirham', 'Checking');
insert into bank (account_number, balance, account_type) values (457287545, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (121892218, 'Naira', 'Savings');
insert into bank (account_number, balance, account_type) values (630718862, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (344011282, 'Guarani', 'Savings');
insert into bank (account_number, balance, account_type) values (881749265, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (204120423, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (929509178, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (54583631, 'Manat', 'Checking');
insert into bank (account_number, balance, account_type) values (644634069, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (381342059, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (406857968, 'Dinar', 'Investment');
insert into bank (account_number, balance, account_type) values (559055081, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (536677927, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (297315961, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (770378491, 'Pula', 'Investment');
insert into bank (account_number, balance, account_type) values (627957581, 'Afghani', 'Checking');
insert into bank (account_number, balance, account_type) values (226831918, 'Balboa', 'Savings');
insert into bank (account_number, balance, account_type) values (697112859, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (27478637, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (448697061, 'Dirham', 'Savings');
insert into bank (account_number, balance, account_type) values (101708731, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (414089382, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (378640956, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (268237449, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (969326673, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (712815923, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (390677604, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (465865883, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (585095086, 'Denar', 'Savings');
insert into bank (account_number, balance, account_type) values (714542477, 'Rupee', 'Savings');
insert into bank (account_number, balance, account_type) values (616709671, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (9504323, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (593468262, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (354903240, 'Colon', 'Savings');
insert into bank (account_number, balance, account_type) values (664670711, 'Afghani', 'Checking');
insert into bank (account_number, balance, account_type) values (386142951, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (279758119, 'Won', 'Checking');
insert into bank (account_number, balance, account_type) values (51998571, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (995368836, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (409440054, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (410360557, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (604167225, 'Dong', 'Investment');
insert into bank (account_number, balance, account_type) values (14403504, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (702494369, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (925577655, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (890869606, 'Lek', 'Investment');
insert into bank (account_number, balance, account_type) values (671015717, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (495990938, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (621031965, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (212867712, 'Pound', 'Checking');
insert into bank (account_number, balance, account_type) values (479759765, 'Tugrik', 'Checking');
insert into bank (account_number, balance, account_type) values (865230776, 'Lek', 'Investment');
insert into bank (account_number, balance, account_type) values (599218991, 'Dirham', 'Savings');
insert into bank (account_number, balance, account_type) values (249048648, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (949434398, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (154296202, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (521608292, 'Ariary', 'Checking');
insert into bank (account_number, balance, account_type) values (55862749, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (869536088, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (90457887, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (462699055, 'Franc', 'Investment');
insert into bank (account_number, balance, account_type) values (999845012, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (667802064, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (168128307, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (37357404, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (304598998, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (579827399, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (229188763, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (825764952, 'Marka', 'Savings');
insert into bank (account_number, balance, account_type) values (276965430, 'Bolivar', 'Checking');
insert into bank (account_number, balance, account_type) values (21746199, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (121024378, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (942526311, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (912671286, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (81510797, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (318704426, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (3941551, 'Denar', 'Checking');
insert into bank (account_number, balance, account_type) values (50113964, 'Yen', 'Checking');
insert into bank (account_number, balance, account_type) values (820232068, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (716818661, 'Rial', 'Checking');
insert into bank (account_number, balance, account_type) values (583982767, 'Koruna', 'Checking');
insert into bank (account_number, balance, account_type) values (575564886, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (467036326, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (9421100, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (597263691, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (984699436, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (711401041, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (407259380, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (774810011, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (479218304, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (933538085, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (526433594, 'Tugrik', 'Checking');
insert into bank (account_number, balance, account_type) values (684272524, 'Yen', 'Checking');
insert into bank (account_number, balance, account_type) values (238144432, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (733567429, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (916438306, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (167562621, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (249556931, 'Franc', 'Savings');
insert into bank (account_number, balance, account_type) values (307818835, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (506428599, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (46684191, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (791675509, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (424471825, 'Rial', 'Savings');
insert into bank (account_number, balance, account_type) values (821072832, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (934434918, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (636422902, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (389502993, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (722020170, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (527518168, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (764240794, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (548075643, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (461972689, 'Birr', 'Checking');
insert into bank (account_number, balance, account_type) values (962737475, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (67016298, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (849310283, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (973127166, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (831056492, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (628304064, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (798173812, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (761609619, 'Ringgit', 'Checking');
insert into bank (account_number, balance, account_type) values (211562417, 'Koruna', 'Checking');
insert into bank (account_number, balance, account_type) values (657669678, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (834272335, 'Won', 'Investment');
insert into bank (account_number, balance, account_type) values (493332655, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (666605740, 'Naira', 'Savings');
insert into bank (account_number, balance, account_type) values (48814475, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (679174737, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (606896010, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (225700098, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (96936667, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (666048905, 'Rial', 'Checking');
insert into bank (account_number, balance, account_type) values (514747769, 'Baht', 'Savings');
insert into bank (account_number, balance, account_type) values (962936894, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (336612843, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (274742319, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (529410616, 'Ringgit', 'Investment');
insert into bank (account_number, balance, account_type) values (154687766, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (332403078, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (656784327, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (874402157, 'Yen', 'Investment');
insert into bank (account_number, balance, account_type) values (903328525, 'Naira', 'Savings');
insert into bank (account_number, balance, account_type) values (872269057, 'Dong', 'Investment');
insert into bank (account_number, balance, account_type) values (44331615, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (856117675, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (399412286, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (668225454, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (748382119, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (92651956, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (120633616, 'Lev', 'Investment');
insert into bank (account_number, balance, account_type) values (735388177, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (953308978, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (960958798, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (749381590, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (915427224, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (124940439, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (945167434, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (143748217, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (309912519, 'Dinar', 'Savings');
insert into bank (account_number, balance, account_type) values (681358205, 'Shilling', 'Savings');
insert into bank (account_number, balance, account_type) values (518472965, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (557007007, 'Lek', 'Checking');
insert into bank (account_number, balance, account_type) values (621899209, 'Hryvnia', 'Checking');
insert into bank (account_number, balance, account_type) values (324672641, 'Litas', 'Checking');
insert into bank (account_number, balance, account_type) values (28534121, 'Dinar', 'Checking');
insert into bank (account_number, balance, account_type) values (853932105, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (21131144, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (734209919, 'Litas', 'Savings');
insert into bank (account_number, balance, account_type) values (347136550, 'Baht', 'Savings');
insert into bank (account_number, balance, account_type) values (218372471, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (319341993, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (641506977, 'Lek', 'Investment');
insert into bank (account_number, balance, account_type) values (679343155, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (333550626, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (684693665, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (46549964, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (648007613, 'Shekel', 'Checking');
insert into bank (account_number, balance, account_type) values (994187214, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (371675206, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (116177556, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (883738549, 'Yen', 'Investment');
insert into bank (account_number, balance, account_type) values (521619763, 'Krona', 'Checking');
insert into bank (account_number, balance, account_type) values (828763933, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (380131725, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (26080880, 'Dong', 'Savings');
insert into bank (account_number, balance, account_type) values (45467433, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (823799491, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (652929243, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (474835865, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (896781782, 'Som', 'Savings');
insert into bank (account_number, balance, account_type) values (501043213, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (700558172, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (195467601, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (100401082, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (149649301, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (540175112, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (346555816, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (66257464, 'Rand', 'Checking');
insert into bank (account_number, balance, account_type) values (100253792, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (142556298, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (816648971, 'Dirham', 'Savings');
insert into bank (account_number, balance, account_type) values (996242997, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (579569021, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (857461034, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (666128181, 'Ringgit', 'Checking');
insert into bank (account_number, balance, account_type) values (311867597, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (931576789, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (718254000, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (893707651, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (255120846, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (669069091, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (984557790, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (181387614, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (51360466, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (405828491, 'Dinar', 'Checking');
insert into bank (account_number, balance, account_type) values (69779912, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (991164135, 'Rial', 'Investment');
insert into bank (account_number, balance, account_type) values (207887121, 'Pound', 'Checking');
insert into bank (account_number, balance, account_type) values (269949273, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (917637347, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (490574491, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (255448393, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (410412079, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (646905373, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (30103895, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (395914500, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (348694928, 'Shilling', 'Checking');
insert into bank (account_number, balance, account_type) values (445094630, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (224583748, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (798917569, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (496109810, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (673486291, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (360085912, 'Dong', 'Investment');
insert into bank (account_number, balance, account_type) values (5416287, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (250907701, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (147124041, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (939186271, 'Franc', 'Investment');
insert into bank (account_number, balance, account_type) values (749287099, 'Rupee', 'Checking');
insert into bank (account_number, balance, account_type) values (847527673, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (172328049, 'Bolivar', 'Savings');
insert into bank (account_number, balance, account_type) values (825274125, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (594274978, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (469272548, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (816912956, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (591099131, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (976673815, 'Birr', 'Investment');
insert into bank (account_number, balance, account_type) values (840469470, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (50481142, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (886077767, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (886346966, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (380298378, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (980148720, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (955524068, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (662810204, 'Rand', 'Investment');
insert into bank (account_number, balance, account_type) values (464763188, 'Quetzal', 'Savings');
insert into bank (account_number, balance, account_type) values (398542049, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (430291431, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (496354603, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (304492059, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (431044084, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (733367026, 'Krona', 'Checking');
insert into bank (account_number, balance, account_type) values (59174443, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (736415092, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (942150863, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (429176304, 'Baht', 'Savings');
insert into bank (account_number, balance, account_type) values (655741272, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (107066109, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (990188613, 'Franc', 'Checking');
insert into bank (account_number, balance, account_type) values (959756856, 'Som', 'Investment');
insert into bank (account_number, balance, account_type) values (472076947, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (829078132, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (846702984, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (983399254, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (91904753, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (773507671, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (994114804, 'Lev', 'Checking');
insert into bank (account_number, balance, account_type) values (80454366, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (609823538, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (526329322, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (23437838, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (494160366, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (504791938, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (625242640, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (765336124, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (335931135, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (737813561, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (199965039, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (395316988, 'Shekel', 'Investment');
insert into bank (account_number, balance, account_type) values (478211014, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (721653458, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (192482490, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (112996838, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (924022224, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (976075009, 'Krona', 'Checking');
insert into bank (account_number, balance, account_type) values (805261821, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (423704166, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (47556601, 'Dirham', 'Checking');
insert into bank (account_number, balance, account_type) values (896945804, 'Krone', 'Checking');
insert into bank (account_number, balance, account_type) values (321341996, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (417302834, 'Afghani', 'Savings');
insert into bank (account_number, balance, account_type) values (339524061, 'Kuna', 'Investment');
insert into bank (account_number, balance, account_type) values (963764821, 'Denar', 'Checking');
insert into bank (account_number, balance, account_type) values (892627665, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (408721193, 'Rial', 'Checking');
insert into bank (account_number, balance, account_type) values (864362645, 'Leu', 'Investment');
insert into bank (account_number, balance, account_type) values (617732344, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (79776749, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (654586153, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (218634263, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (956625319, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (981930867, 'Bolivar', 'Investment');
insert into bank (account_number, balance, account_type) values (745559919, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (44456303, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (735412087, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (852968349, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (646904625, 'Lempira', 'Checking');
insert into bank (account_number, balance, account_type) values (724555730, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (585654535, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (487501799, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (34450215, 'Rupee', 'Savings');
insert into bank (account_number, balance, account_type) values (636528629, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (929786296, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (136649608, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (519329752, 'Rial', 'Checking');
insert into bank (account_number, balance, account_type) values (404380080, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (354747171, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (368397144, 'Taka', 'Checking');
insert into bank (account_number, balance, account_type) values (660081623, 'Krone', 'Checking');
insert into bank (account_number, balance, account_type) values (256211999, 'Krona', 'Investment');
insert into bank (account_number, balance, account_type) values (306915114, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (193019168, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (44565978, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (166911023, 'Dram', 'Investment');
insert into bank (account_number, balance, account_type) values (738793461, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (356536251, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (110154562, 'Rand', 'Savings');
insert into bank (account_number, balance, account_type) values (974333499, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (997395413, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (931309761, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (496149764, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (985763976, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (958997136, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (657838300, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (292450171, 'Dirham', 'Savings');
insert into bank (account_number, balance, account_type) values (963518724, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (18457406, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (414308717, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (419863902, 'Lek', 'Savings');
insert into bank (account_number, balance, account_type) values (760211263, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (847686817, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (441646355, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (579508764, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (85209730, 'Franc', 'Investment');
insert into bank (account_number, balance, account_type) values (855408943, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (728125669, 'Franc', 'Checking');
insert into bank (account_number, balance, account_type) values (352792556, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (415969758, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (62234172, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (856840370, 'Krona', 'Investment');
insert into bank (account_number, balance, account_type) values (227894523, 'Lempira', 'Savings');
insert into bank (account_number, balance, account_type) values (370961202, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (331572060, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (560278553, 'Colon', 'Checking');
insert into bank (account_number, balance, account_type) values (2171323, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (604567957, 'Krone', 'Checking');
insert into bank (account_number, balance, account_type) values (346191371, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (898972041, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (185396251, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (606278875, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (739845238, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (36920419, 'Shilling', 'Checking');
insert into bank (account_number, balance, account_type) values (801028796, 'Somoni', 'Savings');
insert into bank (account_number, balance, account_type) values (737939060, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (60032692, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (36884164, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (131663865, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (106279799, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (921184397, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (255152093, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (168904963, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (712665828, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (888644332, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (143607435, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (327676446, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (394845738, 'Shekel', 'Investment');
insert into bank (account_number, balance, account_type) values (662039126, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (695996528, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (667196774, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (780217224, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (807707278, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (775088848, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (805939450, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (435938640, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (11950457, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (760091653, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (973137874, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (524602993, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (277227523, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (806426457, 'Franc', 'Checking');
insert into bank (account_number, balance, account_type) values (848512842, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (956919865, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (842664813, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (194658507, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (685801419, 'Dong', 'Checking');
insert into bank (account_number, balance, account_type) values (266665392, 'Dinar', 'Checking');
insert into bank (account_number, balance, account_type) values (779740586, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (647086804, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (204864544, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (539664824, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (918002490, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (56883609, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (118604892, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (653892718, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (707038372, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (899508992, 'Manat', 'Savings');
insert into bank (account_number, balance, account_type) values (127786886, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (568188298, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (890915046, 'Yen', 'Investment');
insert into bank (account_number, balance, account_type) values (69879931, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (147618299, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (480762008, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (959279706, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (748219021, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (109276868, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (968259410, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (115939695, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (300457591, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (279424453, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (532220379, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (419528463, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (744375261, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (157869178, 'Sol', 'Investment');
insert into bank (account_number, balance, account_type) values (361861520, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (669397608, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (655377391, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (918495370, 'Ringgit', 'Checking');
insert into bank (account_number, balance, account_type) values (681059041, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (400382766, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (464894588, 'Dinar', 'Savings');
insert into bank (account_number, balance, account_type) values (610107934, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (370216310, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (722507604, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (129857702, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (176785214, 'Shilling', 'Savings');
insert into bank (account_number, balance, account_type) values (709262511, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (62506374, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (486005745, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (530464042, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (772273714, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (805471073, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (518673799, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (608722727, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (878102767, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (850658218, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (730256919, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (499471299, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (319134992, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (189041069, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (173278426, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (466751024, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (539409337, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (662187240, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (481766012, 'Shilling', 'Savings');
insert into bank (account_number, balance, account_type) values (497643477, 'Kuna', 'Savings');
insert into bank (account_number, balance, account_type) values (29594995, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (34747370, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (998997633, 'Rupee', 'Investment');
insert into bank (account_number, balance, account_type) values (135621966, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (607666177, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (933950168, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (764114722, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (674477239, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (973316079, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (704175850, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (534234692, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (764248454, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (442571081, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (742815199, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (330891444, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (556412980, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (931441070, 'Kuna', 'Investment');
insert into bank (account_number, balance, account_type) values (277393475, 'Bolivar', 'Checking');
insert into bank (account_number, balance, account_type) values (746960138, 'Sol', 'Investment');
insert into bank (account_number, balance, account_type) values (588716237, 'Baht', 'Checking');
insert into bank (account_number, balance, account_type) values (839987865, 'Lev', 'Investment');
insert into bank (account_number, balance, account_type) values (475880506, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (79586876, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (884585217, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (616720704, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (104428312, 'Koruna', 'Checking');
insert into bank (account_number, balance, account_type) values (345487628, 'Dong', 'Investment');
insert into bank (account_number, balance, account_type) values (876894145, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (867096091, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (262182916, 'Franc', 'Checking');
insert into bank (account_number, balance, account_type) values (195125678, 'Colon', 'Savings');
insert into bank (account_number, balance, account_type) values (760577415, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (129761584, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (947344379, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (68525940, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (213663009, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (65931779, 'Franc', 'Investment');
insert into bank (account_number, balance, account_type) values (789685980, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (733429422, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (815829608, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (915799337, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (347826259, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (569557856, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (408791123, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (907944831, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (477217543, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (483497710, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (91569065, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (666831748, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (80408165, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (668542752, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (166432530, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (534234764, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (506061062, 'Quetzal', 'Investment');
insert into bank (account_number, balance, account_type) values (826570629, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (865021441, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (666393023, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (423458437, 'Hryvnia', 'Investment');
insert into bank (account_number, balance, account_type) values (386889448, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (710465568, 'Yen', 'Savings');
insert into bank (account_number, balance, account_type) values (774275839, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (147064327, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (37923294, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (655226600, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (928181227, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (555688525, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (506389477, 'Tugrik', 'Investment');
insert into bank (account_number, balance, account_type) values (908810611, 'Krona', 'Checking');
insert into bank (account_number, balance, account_type) values (438240388, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (527897409, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (564033320, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (792667570, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (511543902, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (701163523, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (718822593, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (991023405, 'Yen', 'Checking');
insert into bank (account_number, balance, account_type) values (218435936, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (514589443, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (37269551, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (91365085, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (695847111, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (173521827, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (626717167, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (338086434, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (5662853, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (359003569, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (318425704, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (363061512, 'Manat', 'Savings');
insert into bank (account_number, balance, account_type) values (994354385, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (565863808, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (418442667, 'Pound', 'Savings');
insert into bank (account_number, balance, account_type) values (775654908, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (430834395, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (429494317, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (396399494, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (50683324, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (673396577, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (280836906, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (90643299, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (116239423, 'Lari', 'Savings');
insert into bank (account_number, balance, account_type) values (346120714, 'Afghani', 'Savings');
insert into bank (account_number, balance, account_type) values (965892767, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (323296968, 'Bolivar', 'Checking');
insert into bank (account_number, balance, account_type) values (461659167, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (425338408, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (622856694, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (245194528, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (247643297, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (230575197, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (91827738, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (425755470, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (362545156, 'Dinar', 'Investment');
insert into bank (account_number, balance, account_type) values (983209646, 'Ariary', 'Checking');
insert into bank (account_number, balance, account_type) values (963066221, 'Rial', 'Checking');
insert into bank (account_number, balance, account_type) values (634485957, 'Pound', 'Savings');
insert into bank (account_number, balance, account_type) values (535923621, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (870828073, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (655804075, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (80133186, 'Krone', 'Investment');
insert into bank (account_number, balance, account_type) values (592202355, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (657777713, 'Baht', 'Investment');
insert into bank (account_number, balance, account_type) values (396833428, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (214035819, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (453177511, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (813821133, 'Naira', 'Savings');
insert into bank (account_number, balance, account_type) values (171727301, 'Lev', 'Savings');
insert into bank (account_number, balance, account_type) values (208924408, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (765817630, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (943011346, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (733379227, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (876934403, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (213100545, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (505720065, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (643628913, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (533195888, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (460350424, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (19940127, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (39991774, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (600216155, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (476031547, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (589831375, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (813032618, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (640572559, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (790597145, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (9321528, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (189393908, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (914075771, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (382731364, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (696075422, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (297992160, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (877869574, 'Sol', 'Checking');
insert into bank (account_number, balance, account_type) values (267426313, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (678850611, 'Koruna', 'Investment');
insert into bank (account_number, balance, account_type) values (893657689, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (511592453, 'Krona', 'Checking');
insert into bank (account_number, balance, account_type) values (300336478, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (891450711, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (680140608, 'Franc', 'Savings');
insert into bank (account_number, balance, account_type) values (319413997, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (402036222, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (534066587, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (210254309, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (235636833, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (440967095, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (551438516, 'Real', 'Savings');
insert into bank (account_number, balance, account_type) values (138130874, 'Koruna', 'Checking');
insert into bank (account_number, balance, account_type) values (712188022, 'Shilling', 'Savings');
insert into bank (account_number, balance, account_type) values (955846701, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (827172312, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (95855430, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (705816652, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (449813386, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (686074653, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (738502042, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (322621917, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (610226340, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (965199570, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (804104297, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (872261252, 'Boliviano', 'Savings');
insert into bank (account_number, balance, account_type) values (165368550, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (888614824, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (633062011, 'Zloty', 'Checking');
insert into bank (account_number, balance, account_type) values (386798046, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (178518067, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (426115297, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (798020232, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (791234621, 'Dirham', 'Checking');
insert into bank (account_number, balance, account_type) values (751969332, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (907079592, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (362179864, 'Lev', 'Investment');
insert into bank (account_number, balance, account_type) values (873304971, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (165030874, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (679575045, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (980689606, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (331086800, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (441396237, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (875528284, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (798522677, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (750401922, 'Shekel', 'Savings');
insert into bank (account_number, balance, account_type) values (712969628, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (933866908, 'Marka', 'Savings');
insert into bank (account_number, balance, account_type) values (86587535, 'Sol', 'Savings');
insert into bank (account_number, balance, account_type) values (549340990, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (184769608, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (197943118, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (915806456, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (829394724, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (950959117, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (772098272, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (318557007, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (42836897, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (797217612, 'Manat', 'Checking');
insert into bank (account_number, balance, account_type) values (325198643, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (617721768, 'Dinar', 'Savings');
insert into bank (account_number, balance, account_type) values (319689841, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (961753445, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (836630517, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (954944083, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (282663099, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (791491946, 'Dinar', 'Checking');
insert into bank (account_number, balance, account_type) values (396211742, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (280431798, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (67093239, 'Won', 'Investment');
insert into bank (account_number, balance, account_type) values (427044918, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (579264060, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (719435908, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (676602300, 'Lempira', 'Savings');
insert into bank (account_number, balance, account_type) values (645187082, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (665977216, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (531815356, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (837849972, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (81036725, 'Lari', 'Savings');
insert into bank (account_number, balance, account_type) values (954815959, 'Real', 'Checking');
insert into bank (account_number, balance, account_type) values (517348156, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (275025074, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (415086264, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (35617423, 'Rial', 'Savings');
insert into bank (account_number, balance, account_type) values (690122203, 'Naira', 'Investment');
insert into bank (account_number, balance, account_type) values (508524360, 'Zloty', 'Investment');
insert into bank (account_number, balance, account_type) values (517980526, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (44815645, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (302724778, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (974327067, 'Lek', 'Investment');
insert into bank (account_number, balance, account_type) values (290269691, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (797284659, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (37408446, 'Ruble', 'Savings');
insert into bank (account_number, balance, account_type) values (528872553, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (371416994, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (551488275, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (993167838, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (647927735, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (432503163, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (22884424, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (576002409, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (150462035, 'Peso', 'Investment');
insert into bank (account_number, balance, account_type) values (264956555, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (368600279, 'Krone', 'Investment');
insert into bank (account_number, balance, account_type) values (942545735, 'Euro', 'Checking');
insert into bank (account_number, balance, account_type) values (169595505, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (644762961, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (983953096, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (454419963, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (466490612, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (806748460, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (999917587, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (936687677, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (386348478, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (284801227, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (672406377, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (361512007, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (996636285, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (616772872, 'Balboa', 'Savings');
insert into bank (account_number, balance, account_type) values (278567275, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (523541863, 'Manat', 'Investment');
insert into bank (account_number, balance, account_type) values (87701938, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (541036665, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (765508405, 'Somoni', 'Checking');
insert into bank (account_number, balance, account_type) values (889052830, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (359576488, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (403960657, 'Dollar', 'Investment');
insert into bank (account_number, balance, account_type) values (939125958, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (401542161, 'Ringgit', 'Savings');
insert into bank (account_number, balance, account_type) values (282744014, 'Dollar', 'Checking');
insert into bank (account_number, balance, account_type) values (169499967, 'Tugrik', 'Investment');
insert into bank (account_number, balance, account_type) values (141740626, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (793807791, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (34742678, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (832725753, 'Somoni', 'Savings');
insert into bank (account_number, balance, account_type) values (32876707, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (566399985, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (95782360, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (453070741, 'Euro', 'Savings');
insert into bank (account_number, balance, account_type) values (285535470, 'Krona', 'Investment');
insert into bank (account_number, balance, account_type) values (693426940, 'Cordoba', 'Savings');
insert into bank (account_number, balance, account_type) values (250645914, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (635230226, 'Lev', 'Savings');
insert into bank (account_number, balance, account_type) values (744105394, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (304197436, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (6876513, 'Real', 'Investment');
insert into bank (account_number, balance, account_type) values (169964384, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (174340503, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (827292852, 'Rupee', 'Savings');
insert into bank (account_number, balance, account_type) values (504139168, 'Quetzal', 'Investment');
insert into bank (account_number, balance, account_type) values (737025095, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (705106434, 'Riels', 'Investment');
insert into bank (account_number, balance, account_type) values (371787569, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (924627849, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (312098870, 'Ruble', 'Investment');
insert into bank (account_number, balance, account_type) values (548824563, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (234308517, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (897768209, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (941443308, 'Hryvnia', 'Savings');
insert into bank (account_number, balance, account_type) values (98468999, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (310632114, 'Pound', 'Investment');
insert into bank (account_number, balance, account_type) values (846369475, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (168759806, 'Peso', 'Checking');
insert into bank (account_number, balance, account_type) values (110086408, 'Zloty', 'Savings');
insert into bank (account_number, balance, account_type) values (739375290, 'Naira', 'Savings');
insert into bank (account_number, balance, account_type) values (989893359, 'Rupiah', 'Checking');
insert into bank (account_number, balance, account_type) values (638085749, 'Euro', 'Investment');
insert into bank (account_number, balance, account_type) values (243636426, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (138167655, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (421662907, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (152496804, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (25054319, 'Rupiah', 'Investment');
insert into bank (account_number, balance, account_type) values (939041262, 'Pound', 'Investment');
insert into bank (account_number, balance, account_type) values (696600947, 'Dram', 'Checking');
insert into bank (account_number, balance, account_type) values (770243611, 'Yuan Renminbi', 'Savings');
insert into bank (account_number, balance, account_type) values (402826749, 'Peso', 'Savings');
insert into bank (account_number, balance, account_type) values (473055123, 'Hryvnia', 'Checking');
insert into bank (account_number, balance, account_type) values (449007280, 'Krona', 'Savings');
insert into bank (account_number, balance, account_type) values (495343124, 'Dollar', 'Savings');
insert into bank (account_number, balance, account_type) values (255942488, 'Gourde', 'Investment');
insert into bank (account_number, balance, account_type) values (930370448, 'Yuan Renminbi', 'Investment');
insert into bank (account_number, balance, account_type) values (532665288, 'Franc', 'Savings');
insert into bank (account_number, balance, account_type) values (417260352, 'Kuna', 'Checking');
insert into bank (account_number, balance, account_type) values (443236155, 'Rand', 'Checking');
insert into bank (account_number, balance, account_type) values (890545684, 'Rand', 'Savings');
insert into bank (account_number, balance, account_type) values (266546456, 'Ruble', 'Checking');
insert into bank (account_number, balance, account_type) values (594733787, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (974399676, 'Yuan Renminbi', 'Checking');
insert into bank (account_number, balance, account_type) values (706466528, 'Baht', 'Savings');
insert into bank (account_number, balance, account_type) values (601772933, 'Rupiah', 'Savings');
insert into bank (account_number, balance, account_type) values (61663142, 'Ruble', 'Checking');
